name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: blog-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.BLOG }}
          TARGET_REPO: qinghuanI/qinghuanI.github.io
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: yarn && yarn run build
          BUILD_DIR: blog/.vuepress/dist
          CNAME: https://www.qinghuani.fun